version: "3.8"
services:
  osrs_tracker_frontend:
    image: your-repository/osrs_tracker_frontend:latest # replace with your actual image name and tag
    environment:
      - HOST_URL=${HOST_URL}
      - SITE_TITLE=${SITE_TITLE:-OSRS Group Tracker}
      - SITE_NAME=${SITE_NAME:-GroupIron.men}
    restart: always
    depends_on:
      - "osrs_tracker_backend"
    ports:
      - 4000:4000 # replace this if using a docker-compatible reverse proxy like traefik
  osrs_tracker_backend:
    image: your-repository/osrs_tracker_backend:latest # replace with your actual image name and tag
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - BACKEND_SECRET=${BACKEND_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID:-}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET:-}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI:-}
      - DISCORD_AUTO_REGISTRATION=${DISCORD_AUTO_REGISTRATION:-false}
      - DISCORD_AUTOREG_SERVERS=${DISCORD_AUTOREG_SERVERS:-}
    restart: always
    depends_on:
      - "postgres"
    ports:
      - 5000:8080  # replace this if using a docker-compatible reverse proxy like traefik
  postgres:
    image: postgres
    restart: always
    container_name: group-ironmen-tracker-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

